### ISSUE TITLE
HDMI output not working correctly

### ISSUE THREAD

**Issue by shendes** [cutiepi-io/cutiepi-shell#11]
The HDMI output is not working correctly.
Using the same cable on RP400 und RP4 works without problems.
***BUT*** I use a micro HDMI to HDMI adapter and when wiggleing the adapter half way out - sometimes i get a picture on the monitor.

**Comment by penk** [comment]
@shendes thank you, this is a known issue in the current Bullseye image, we are looking into it.

**Comment by penk** [comment]
HDMI output works with 5.15 kernel, I'll close this bug for now.

**Comment by Palmiga** [comment]
Sidekick-mode did not start here. It should start, whenever I plugged in an hdmi-cable, shouldn't it?
Or did I need to start it in any other way? My monitor shows nothing and stay dark.

**Comment by penk** [comment]
@Palmiga HDMI output works, but SideKick mode implementation hasn't been added yet.

**Comment by Palmiga** [comment]
HDMI didnt work here. I am not able to choose and activate it.
