### ISSUE TITLE
Battery indecator drops to zero within seconds of unplugging

### ISSUE THREAD

**Issue by Notsonoble** [cutiepi-io/cutiepi-shell#20]
As soon as I unplug a charging  cable from my cutiepi, the battery indicator drops from 80 to 0 in increments of 5%, it obviously has some capacity, because it doesn't shutdown. A fresh install of the most recent image still does this.

**Comment by imaclmaca** [comment]
I see a variation on this - the level drops off very quickly, but often then seems to creep back up after a while.

Determining the charge level of LiIon batteries is hard....

**Comment by imaclmaca** [comment]
Further to this - I was away for a few days, so my Cutiepi was unused: It was fuly charged when I left it, but after 4 days switched off, the battery was showing 10%. 
That does not seem reasonable for a LiIon battery - is something wrong?
Is the tablet "fully off" when it is off? Or is it actually in some sort of standby low power state and still using the battery?

**Comment by penk** [comment]
Fixed the indicator in latest image, I'm closing this one. 
https://github.com/cutiepi-io/pi-gen_stage4.5-cutiepi/releases/tag/2022-04-01
