### ISSUE TITLE
Wrong display orientation when system default changed: CutiePi

### ISSUE THREAD

**Issue by ASMotionLab** [cutiepi-io/cutiepi-shell#9]
Hi, 
By default, Raspbian is set to be portrait when it boots, and the CutiePi shell appears correctly (in landscape), and auto-orientates itself.
But I'd like Raspbian to be landscape by default, so I change it via Preferences > Screen Configuration. DSI-1 > Orientation > Left.
Now, the CutiePi shell is 90 degrees out. So when tablet is landscape, CutiePi shell is portrait. When I rotate the table, it always seems to be 90 degrees out. Is there a way to set it to 0?

Thanks

**Comment by penk** [comment]
Fixed in commit a1b267a7dd5d49fb6d05a8360e689db21b440340

Released in image 2022-01-23 
https://github.com/cutiepi-io/pi-gen_stage4.5-cutiepi/releases/tag/2022-01-23
